export const canonicalExerciseNames = [
  "Ab Wheel Rollout",
  "Arnold Press",
  "Back Extension",
  "Barbell Bench Press",
  "Barbell Curl",
  "Barbell Front Squat",
  "Barbell Hip Thrust",
  "Barbell Lunge",
  "Barbell Overhead Press",
  "Barbell Romanian Deadlift",
  "Barbell Row",
  "Barbell Shrug",
  "Barbell Skull Crusher",
  "Barbell Squat",
  "Barbell Step-Up",
  "Bulgarian Split Squat",
  "Bulgarian Biceps Curl",
  "Bayesian Cable Curl",
  "Cable Chest Fly",
  "Cable Crunch",
  "Cable Curl",
  "Cable Face Pull",
  "Cable Hammer Curl",
  "Cable Lateral Raise",
  "Cable Pushdown",
  "Cable Rear Delt Fly",
  "Cable Row",
  "Cable Wood Chop",
  "Chest Dip",
  "Chest Press Machine",
  "Close-Grip Bench Press",
  "Crunch",
  "Dead Bug",
  "Deadlift",
  "Decline Bench Press",
  "Deficit Deadlift",
  "Donkey Calf Raise",
  "Dumbbell Bench Press",
  "Dumbbell Bulgarian Split Squat",
  "Dumbbell Curl",
  "Dumbbell Fly",
  "Dumbbell Front Raise",
  "Dumbbell Hammer Curl",
  "Dumbbell Hip Thrust",
  "Dumbbell Incline Bench Press",
  "Dumbbell Lateral Raise",
  "Dumbbell Lunge",
  "Dumbbell Overhead Press",
  "Dumbbell Pullover",
  "Dumbbell Rear Delt Fly",
  "Dumbbell Romanian Deadlift",
  "Dumbbell Row",
  "Dumbbell Shoulder Press",
  "Dumbbell Shrug",
  "Dumbbell Split Squat",
  "Dumbbell Step-Up",
  "EZ-Bar Curl",
  "EZ-Bar Skull Crusher",
  "Flat Bench Press",
  "Front Plank",
  "Front Raise",
  "Glute Bridge",
  "Goblet Squat",
  "Good Morning",
  "Hack Squat",
  "Hammer Curl",
  "Hanging Knee Raise",
  "Hanging Leg Raise",
  "High-Bar Squat",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Hip Thrust",
  "Incline Bench Press",
  "Incline Dumbbell Curl",
  "Incline Dumbbell Press",
  "Incline Machine Press",
  "Incline Push-Up",
  "JM Press",
  "Kettlebell Goblet Squat",
  "Kettlebell Romanian Deadlift",
  "Kettlebell Swing",
  "Landmine Press",
  "Lat Pulldown",
  "Leg Curl",
  "Leg Extension",
  "Leg Press",
  "Lying Leg Curl",
  "Lying Biceps Curl",
  "Machine Calf Raise",
  "Machine Chest Press",
  "Machine Curl",
  "Machine Preacher Curl",
  "Machine Row",
  "Military Press",
  "Neutral-Grip Pulldown",
  "Nordic Hamstring Curl",
  "Overhead Cable Triceps Extension",
  "Overhead Dumbbell Triceps Extension",
  "Pallof Press",
  "Pendlay Row",
  "Pec Deck",
  "Preacher Dumbbell Curl",
  "Preacher Curl",
  "Pull-Up",
  "Push Press",
  "Push-Up",
  "Rear Delt Fly",
  "Reverse Crunch",
  "Reverse Fly Machine",
  "Reverse Lunge",
  "Romanian Deadlift",
  "Russian Twist",
  "Seated Calf Raise",
  "Seated Cable Row",
  "Seated Dumbbell Curl",
  "Seated Dumbbell Press",
  "Seated Hamstring Curl",
  "Seated Leg Curl",
  "Seated Leg Extension",
  "Seated Row Machine",
  "Shoulder Press Machine",
  "Side Lateral Raise",
  "Side Plank",
  "Single-Arm Cable Row",
  "Single-Arm Dumbbell Row",
  "Single-Leg Romanian Deadlift",
  "Smith Machine Bench Press",
  "Smith Machine Incline Press",
  "Smith Machine Row",
  "Smith Machine Squat",
  "Spider Curl",
  "Split Squat",
  "Standing Calf Raise",
  "Standing Cable Crunch",
  "Standing Dumbbell Curl",
  "Standing Hammer Curl",
  "Standing Leg Curl",
  "Stiff-Leg Deadlift",
  "Sumo Deadlift",
  "T-Bar Row",
  "Trap Bar Deadlift",
  "Triceps Cross",
  "Triceps Dip",
  "Triceps Pulldown",
  "Triceps Pushdown",
  "Upright Row",
  "Walking Lunge",
  "Weighted Chin-Up",
  "Weighted Dip",
  "Weighted Pull-Up",
  "Wide-Grip Lat Pulldown",
  "Shrug"
] as const;

export const priorityExerciseNames = [
  "Barbell Bench Press",
  "Barbell Curl",
  "Barbell Overhead Press",
  "Barbell Row",
  "Barbell Squat",
  "Bulgarian Split Squat",
  "Cable Chest Fly",
  "Cable Curl",
  "Cable Face Pull",
  "Cable Lateral Raise",
  "Cable Pushdown",
  "Cable Row",
  "Chest Press Machine",
  "Dumbbell Bench Press",
  "Dumbbell Curl",
  "Dumbbell Fly",
  "Dumbbell Hammer Curl",
  "Dumbbell Incline Bench Press",
  "Dumbbell Lateral Raise",
  "Dumbbell Overhead Press",
  "Dumbbell Romanian Deadlift",
  "Dumbbell Row",
  "Dumbbell Shoulder Press",
  "EZ-Bar Curl",
  "Flat Bench Press",
  "Goblet Squat",
  "Hammer Curl",
  "Hip Thrust",
  "Incline Bench Press",
  "Incline Dumbbell Press",
  "Lat Pulldown",
  "Leg Curl",
  "Leg Extension",
  "Leg Press",
  "Machine Chest Press",
  "Machine Row",
  "Pec Deck",
  "Preacher Curl",
  "Pull-Up",
  "Push-Up",
  "Rear Delt Fly",
  "Romanian Deadlift",
  "Seated Cable Row",
  "Seated Dumbbell Curl",
  "Seated Dumbbell Press",
  "Shoulder Press Machine",
  "Smith Machine Bench Press",
  "Smith Machine Squat",
  "Split Squat",
  "Standing Calf Raise",
  "Sumo Deadlift",
  "T-Bar Row",
  "Trap Bar Deadlift",
  "Triceps Dip",
  "Walking Lunge",
  "Weighted Dip",
  "Weighted Pull-Up",
  "Wide-Grip Lat Pulldown"
] as const;

export const blockedExerciseNames = [
  "asdf",
  "foo",
  "foobar",
  "null",
  "placeholder",
  "qwerty",
  "sample",
  "test",
  "testing",
  "todo",
  "unknown",
  "xxx"
] as const;

export const blockedExerciseWordFragments = [
  // Match whole words only. Keep this list free of short substrings so
  // legitimate movement names like "assisted pull-up" never get caught.
  "anus",
  "bastard",
  "bitch",
  "boob",
  "bollock",
  "boner",
  "clit",
  "cock",
  "coon",
  "cum",
  "cunt",
  "dick",
  "dildo",
  "fag",
  "faggot",
  "fuck",
  "gooch",
  "hitler",
  "idiot",
  "jizz",
  "kike",
  "motherfucker",
  "nigga",
  "nigger",
  "nazi",
  "penis",
  "porn",
  "pussy",
  "rape",
  "rapist",
  "retard",
  "shit",
  "slut",
  "spic",
  "testicle",
  "twat",
  "whore",
  /// More words:
  "anus",
  "arse",
  "asshole",
  "bastard",
  "bitch",
  "boob",
  "boobs",
  "boner",
  "bullshit",
  "buttplug",
  "butt plug",
  "clit",
  "cock",
  "coochie",
  "crap",
  "cum",
  "cumming",
  "cums",
  "cunt",
  "dick",
  "dildo",
  "dipshit",
  "douche",
  "douchebag",
  "ejaculate",
  "fag",
  "faggot",
  "fart",
  "fellatio",
  "fuck",
  "fucked",
  "fucker",
  "fucking",
  "gangbang",
  "genital",
  "genitals",
  "handjob",
  "hardon",
  "hard on",
  "hentai",
  "horny",
  "jackoff",
  "jerkoff",
  "jizz",
  "kys",
  "masturbate",
  "milf",
  "motherfucker",
  "naked",
  "nipple",
  "nipples",
  "nude",
  "nudes",
  "orgasm",
  "penis",
  "porn",
  "porno",
  "pornhub",
  "pussy",
  "queef",
  "rape",
  "rapist",
  "rectum",
  "rimjob",
  "scrotum",
  "semen",
  "sex",
  "sexy",
  "shit",
  "shitty",
  "slut",
  "smegma",
  "spank",
  "sperm",
  "testicle",
  "testicles",
  "titjob",
  "tits",
  "twat",
  "vagina",
  "vibrator",
  "wank",
  "wanker",
  "whore",

  "69",
  "420",
  "6-7",
  "67",
  "six seven",
  "skibidi",
  "skibidi toilet",
  "sigma",
  "gyatt",
  "gyat",
  "rizz",
  "ohio",
  "only in ohio",
  "brainrot",
  "brain rot",
  "delulu",
  "sus",
  "amogus",
  "among us",
  "imposter",
  "sussy",
  "bussin",
  "gooning",
  "looksmaxxing",
  "mogging",
  "mewing",
  "edging",
  "fanum tax",
  "alpha male",
  "beta male",
  "chad",
  "gigachad",
  "big chungus",
  "chungus",
  "rickroll",
  "rick astley",
  "never gonna give you up",
  "deez nuts",
  "ligma",
  "sugma",
  "updog",
  "joe mama",
  "your mom",
  "yo mama",
  "trollface",
  "ragebait",
  "rage bait",
  "ratio",
  "cope",
  "seethe",
  "skill issue",
  "touch grass",
  "npc",
  "bot",
  "l bozo",
  "bozo",
  "cringe",
  "based",
  "yeet",
  "yeeted",
  "dab",
  "dababy",
  "fortnite",
  "amongus",
  "sus exercise",
  "sigma grindset",
  "griddy",
  "grimace shake",
  "big netanyahu",
  "big netanjahu",
  "netanyahu",
  "netanjahu",
  "putin",
  "trump",
  "biden",
  "hitler",
  "stalin",
  "mussolini",
  "nazi",
  "swastika",
  "heil",
  "kkk",
  "isis",
  "taliban",
  "hamas",
  "terrorist",
  "terrorism",

  "admin",
  "administrator",
  "moderator",
  "mod",
  "official",
  "support",
  "system",
  "root",
  "null",
  "undefined",
  "delete",
  "drop table",
  "select *",
  "script",
  "<script",
  "javascript:",
  "onerror",
  "onclick",
  "eval(",
  "alert(",
  "localhost",
  "127.0.0.1"
] as const;
