"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { HudButton, Panel } from "../../shared/ui/ui";
import { InfoPopover } from "../../shared/ui/info-popover";
import { useOnboarding } from "./use-onboarding";

const checklist = [["tour", "Understand the app navigation"], ["practice", "Complete the private practice workout"], ["startWorkout", "Start a real workout"], ["logEditSet", "Log or edit a real set"], ["finishWorkout", "Finish a real workout"], ["history", "Locate History"], ["progress", "Locate Progress"], ["volume", "Locate Volume"]] as const;

export function HelpScreen(): ReactNode {
  const { onboarding, mark, resetTour } = useOnboarding();
  return <div className="mx-auto max-w-3xl space-y-4 p-4 lg:p-6"><header><p className="label-caps text-outline">GETTING_STARTED</p><h1 className="font-display text-2xl font-bold text-fg">Help & Tutorial</h1><p className="mt-2 text-sm text-fg-muted">Guidance is repeatable and practice data never enters workout history or analytics.</p></header><Panel accent="cyan" eyebrow="FOUNDING_MEMBER_CHECKLIST"><ul className="space-y-2">{checklist.map(([key, label]) => <li className="flex min-h-11 items-center gap-3 rounded border border-outline-dim/50 px-3" key={key}><span className={onboarding?.steps[key] ? "text-green" : "text-outline"}>{onboarding?.steps[key] ? "✓" : "○"}</span><span className="text-sm text-fg">{label}</span></li>)}</ul><HudButton className="mt-4 w-full" onClick={() => { void resetTour().then(() => { window.sessionStorage.setItem("gym:replay-tour", "1"); window.location.assign("/"); }); }} variant="outline">REPLAY GUIDED TOUR</HudButton></Panel><PracticeWorkout onComplete={() => void mark("practice")} /><Panel accent="lavender" eyebrow="QUICK_REFERENCE"><div className="space-y-3 text-sm text-fg-muted"><p><strong className="text-fg">Working vs warmup</strong><InfoPopover label="set types">Working sets drive weekly volume and strength progress. Warmups remain in history but do not count toward muscle volume.</InfoPopover></p><p><strong className="text-fg">RIR</strong><InfoPopover label="reps in reserve">RIR estimates how many clean repetitions remained. 0 means none; 2 means roughly two remained.</InfoPopover></p><p><strong className="text-fg">Estimated 1RM</strong><InfoPopover label="estimated one rep max">A calculated estimate from load and reps, useful for trends but not an exact performance measurement.</InfoPopover></p><p><strong className="text-fg">Weekly volume</strong><InfoPopover label="weekly volume">Counts working sets using each exercise’s current primary-muscle assignments.</InfoPopover></p></div></Panel><Panel accent="none" eyebrow="MORE_HELP"><div className="grid gap-2 text-sm"><Link className="text-cyan" href="/workouts">History & CSV guide →</Link><Link className="text-cyan" href="/privacy">Privacy, storage, export & deletion →</Link><Link className="text-cyan" href="/support">Contact support & status →</Link></div></Panel></div>;
}

function PracticeWorkout({ onComplete }: { onComplete: () => void }): ReactNode {
  const [step, setStep] = useState(0);
  return <Panel accent="lavender" eyebrow="NON_PERSISTENT_PRACTICE_WORKOUT"><p className="text-sm text-fg">{step === 0 ? "1. Select the example Bench Press exercise." : step === 1 ? "2. Log a practice working set: 20 kg × 8 reps, RIR 2." : step === 2 ? "3. Edit the practice set to 22.5 kg." : step === 3 ? "4. Finish the practice workout." : "Practice complete. Nothing was saved to your account."}</p><div className="mt-4 rounded border border-outline-dim/60 bg-surface-low/50 p-3 text-xs text-fg-muted">{step === 0 ? "EXERCISE_CATALOG · Bench Press" : step === 1 ? "WORKING · 20 KG · 8 REPS · RIR 2" : step === 2 ? "EDIT_SET · 22.5 KG · 8 REPS · RIR 2" : step === 3 ? "1 EXERCISE · 1 SET · READY_TO_FINISH" : "PRACTICE_COMPLETE ✓"}</div>{step < 4 ? <HudButton className="mt-4 w-full" onClick={() => { const next = step + 1; setStep(next); if (next === 4) onComplete(); }}>{step === 0 ? "SELECT EXERCISE" : step === 1 ? "SAVE PRACTICE SET" : step === 2 ? "SAVE PRACTICE EDIT" : "FINISH PRACTICE"}</HudButton> : <HudButton className="mt-4 w-full" onClick={() => setStep(0)} variant="outline">REPEAT PRACTICE</HudButton>}</Panel>;
}
